import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_nav/page";
import Footer from "./_footer/page";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
  <html lang="en">
    <head>
      <title>Omar Moussa | Frontend Developer</title>
      <meta name="description" content="Frontend Developer specializing in React, Next.js, and modern UI design." />
    </head>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ThemeProvider>
        <NavBar />
        {children}
        <Footer />
      </ThemeProvider>
    </body>
  </html>
);
}
